apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: user-record-service
data:
  DATABASE_HOST: postgres-service
  DATABASE_PORT: "5432"
  DATABASE_NAME: user_db
  SPRING_APP_NAME: "User Management Service"
  APP_PORT: "9090"
  JPA_SHOW_SQL: "false"
  HIBERNATE_FORMAT_SQL: "false"

  # HikariCP Pooling Configuration
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "10"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "30000"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "20000"